### PR TITLE
WIP: add pangeo css

### PR DESCRIPTION
**Pull request by rabernat**
This is a first pass at adding some Pangeo style to this site.

Lots more to do here, but this should help us get started.

image

### CODE REVIEW

**Comment by charlesbluca** [comment]
This looks great! Thanks @rabernat.

As a sidenote, I'll have to figure out some CI for this repo so it's easier to check PRs.

**Comment by rabernat** [comment]
Eventually we will want to add some testing to the app: https://flask.palletsprojects.com/en/1.1.x/testing/

If you merge this, will it automatically deploy?

**Comment by charlesbluca** [comment]
Yes, this would get deployed automatically - would it be better to get some kind of testing in order before we merge this one?

**Comment by rabernat** [comment]
> would it be better to get some kind of testing in order before we merge this one?

I can see that potentially taking lots of time. We are on ticking clock to get something deployed, since the old catalog site is broken.

**Comment by charlesbluca** [comment]
Yeah, that's something we can look into once we have more time.

For now, your branch looks good to me so I'll go ahead and merge it.

**Pull request merged**
